#!/bin/bash

# move this script to the .git/hooks directory for your repo.
# make sure to chmod +x .git/hooks/commit-msg

repo=$(basename `git rev-parse --show-toplevel`)
branch=`git rev-parse --abbrev-ref HEAD`

if [[ $branch == issues/* ]]; then
  issue=$(echo "$branch" | awk -F/ '{ print $2 }')
  link="[endlessm/$repo#$issue]"
  echo "issue link: $link"
  echo $link >> $1
fi

exit 0
